# Generated by Django 2.0.7 on 2018-07-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orange_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopAuditLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shop_id', models.IntegerField()),
                ('auth', models.IntegerField()),
                ('remark', models.CharField(max_length=255)),
                ('operator_id', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'shop_audit_log',
                'managed': False,
            },
        ),
    ]
