# Generated by Django 2.0.7 on 2018-07-26 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orange_manage', '0002_shopauditlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopauditlog',
            options={},
        ),
    ]
