# Generated by Django 2.0.7 on 2018-07-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orange_manage', '0003_auto_20180726_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopauditlog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
