# Generated by Django 2.0.7 on 2018-07-29 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orange_manage', '0004_auto_20180726_2018'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopAuditLog',
        ),
    ]
